name: Java Selenium CI with Juice Shop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Start Juice Shop Docker container
        run: |
          docker pull bkimminich/juice-shop:v13.2.0
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop:v13.2.0

      - name: Wait for Juice Shop to be healthy
        run: |
          for i in {1..30}; do
            curl -sSf http://localhost:3000 && break
            echo "Waiting for Juice Shop..."
            sleep 5
          done

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-html-report
          path: gradle-junit-selenium/build/reports/tests/test
